jobs:
- job: Build_Go
  timeoutInMinutes: 90
  pool:
    name: Azure Pipelines
    vmImage: ubuntu-latest
  steps:
  - checkout: self
    
  - task: PowerShell@2
    displayName: 'Build Go $(Version)'
    inputs:
      targetType: filePath
      filePath: './builders/build-go.ps1'
      arguments: '-Version $(Version) -Platform $(Platform) -Architecture $(Architecture)'

  - task: PublishPipelineArtifact@1
    displayName: 'Publish Artifact: Go $(Version)'
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)' 
      artifactName: 'go-$(Version)-$(Platform)-$(Architecture)'